# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f1fc25c864f7d96bd67b502c8d26222e8d57b7d40268bebe99dc91d62f1ab174b9c288cd9d43b76862e25b3f1b3f4c8a451c6ead62c2d6ca25167a6cc01ecd12

test:
  secret_key_base: 8a39d01719fbc7a8e2dfb5c9f6449e8f8fa370c604148828c65d25d77a2ac902da8161586859fa48da61f825258e134ad307c64fb0a962d0596c28bcb42b14cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
